version: '2.0'
services:
  reservation:
    build: ./reservation
    ports:
    - "8082:8082"
    links:
      - eureka-server
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
    depends_on:
      - "eureka-server"
  imageprocessing:
    build: ./image-recognition
    ports:
    - "8081:8081"
    links:
      - eureka-server
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - AWS_ACCESS
      - AWS_SECRET
      - AWS_BUCKET
    depends_on:
      - "eureka-server"
  office:
    build: ./office-service
    ports:
    - "8083:8083"
    links:
      - eureka-server
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
    depends_on:
      - "eureka-server"
  eureka-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
